<div class="col-md-9 guide-content">
<h1>Fixtures <a href="http://www.yiiframework.com/doc-2.0/guide-test-fixture.html#fixtures" name="fixtures">&para;</a></h1>
<p>Fixtures are important part of testing. Their main purpose is to set up the environment in a fixed/known state so that your tests are repeatable and run in an expected way. Yii provides a fixture framework that allows you to define your fixtures precisely and use them easily.</p>
<p>A key concept in the Yii fixture framework is the so-called <em>fixture objects</em>. A fixture object represents a particular aspect of a test environment and is an instance of <a href="http://www.yiiframework.com/doc-2.0/yii-test-fixture.html">yii\test\Fixture</a> or its child class. For example, you may use <code>UserFixture</code> to make sure the user DB table contains a fixed set of data. You load one or multiple fixture objects before running a test and unload them when finishing.</p>
<p>A fixture may depend on other fixtures, specified via its <a href="http://www.yiiframework.com/doc-2.0/yii-test-fixture.html#$depends-detail">yii\test\Fixture::$depends</a> property. When a fixture is being loaded, the fixtures it depends on will be automatically loaded BEFORE the fixture; and when the fixture is being unloaded, the dependent fixtures will be unloaded AFTER the fixture.</p>
<h2>Defining a Fixture <a href="http://www.yiiframework.com/doc-2.0/guide-test-fixture.html#defining-a-fixture" name="defining-a-fixture">&para;</a></h2>
<p>To define a fixture, create a new class by extending <a href="http://www.yiiframework.com/doc-2.0/yii-test-fixture.html">yii\test\Fixture</a> or <a href="http://www.yiiframework.com/doc-2.0/yii-test-activefixture.html">yii\test\ActiveFixture</a>. The former is best suited for general purpose fixtures, while the latter has enhanced features specifically designed to work with database and ActiveRecord.</p>
<p>The following code defines a fixture about the <code>User</code> ActiveRecord and the corresponding user table.</p>
<pre><code class="language-php"><span style="color: #0000bb;">&lt;?php<br /></span><span style="color: #007700;">namespace&nbsp;</span><span style="color: #0000bb;">app</span><span style="color: #007700;">\</span><span style="color: #0000bb;">tests</span><span style="color: #007700;">\</span><span style="color: #0000bb;">fixtures</span><span style="color: #007700;">;<br /><br />use&nbsp;</span><span style="color: #0000bb;">yii</span><span style="color: #007700;">\</span><span style="color: #0000bb;">test</span><span style="color: #007700;">\</span><span style="color: #0000bb;">ActiveFixture</span><span style="color: #007700;">;<br /><br />class&nbsp;</span><span style="color: #0000bb;">UserFixture&nbsp;</span><span style="color: #007700;">extends&nbsp;</span><span style="color: #0000bb;">ActiveFixture<br /></span><span style="color: #007700;">{<br />&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;</span><span style="color: #0000bb;">$modelClass&nbsp;</span><span style="color: #007700;">=&nbsp;</span><span style="color: #dd0000;">'app\models\User'</span><span style="color: #007700;">;<br />}</span></code></pre>
<blockquote>
<p>Tip: Each <code>ActiveFixture</code> is about preparing a DB table for testing purpose. You may specify the table by setting either the <a href="http://www.yiiframework.com/doc-2.0/yii-test-activefixture.html#$tableName-detail">yii\test\ActiveFixture::$tableName</a> property or the <a href="http://www.yiiframework.com/doc-2.0/yii-test-baseactivefixture.html#$modelClass-detail">yii\test\ActiveFixture::$modelClass</a> property. If the latter, the table name will be taken from the <code>ActiveRecord</code> class specified by <code>modelClass</code>.</p>
</blockquote>
<p>The fixture data for an <code>ActiveFixture</code> fixture is usually provided in a file located at <code>FixturePath/data/TableName.php</code>, where <code>FixturePath</code> stands for the directory containing the fixture class file, and <code>TableName</code> is the name of the table associated with the fixture. In the example above, the file should be <code>@app/tests/fixtures/data/user.php</code>. The data file should return an array of data rows to be inserted into the user table. For example,</p>
<pre><code class="language-php"><span style="color: #0000bb;">&lt;?php<br /></span><span style="color: #007700;">return&nbsp;[<br />&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #dd0000;">'user1'&nbsp;</span><span style="color: #007700;">=&gt;&nbsp;[<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #dd0000;">'username'&nbsp;</span><span style="color: #007700;">=&gt;&nbsp;</span><span style="color: #dd0000;">'lmayert'</span><span style="color: #007700;">,<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #dd0000;">'email'&nbsp;</span><span style="color: #007700;">=&gt;&nbsp;</span><span style="color: #dd0000;">'strosin.vernice@jerde.com'</span><span style="color: #007700;">,<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #dd0000;">'auth_key'&nbsp;</span><span style="color: #007700;">=&gt;&nbsp;</span><span style="color: #dd0000;">'K3nF70it7tzNsHddEiq0BZ0i-OU8S3xV'</span><span style="color: #007700;">,<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #dd0000;">'password'&nbsp;</span><span style="color: #007700;">=&gt;&nbsp;</span><span style="color: #dd0000;">'$2y$13$WSyE5hHsG1rWN2jV8LRHzubilrCLI5Ev/iK0r3jRuwQEs2ldRu.a2'</span><span style="color: #007700;">,<br />&nbsp;&nbsp;&nbsp;&nbsp;],<br />&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #dd0000;">'user2'&nbsp;</span><span style="color: #007700;">=&gt;&nbsp;[<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #dd0000;">'username'&nbsp;</span><span style="color: #007700;">=&gt;&nbsp;</span><span style="color: #dd0000;">'napoleon69'</span><span style="color: #007700;">,<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #dd0000;">'email'&nbsp;</span><span style="color: #007700;">=&gt;&nbsp;</span><span style="color: #dd0000;">'aileen.barton@heaneyschumm.com'</span><span style="color: #007700;">,<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #dd0000;">'auth_key'&nbsp;</span><span style="color: #007700;">=&gt;&nbsp;</span><span style="color: #dd0000;">'dZlXsVnIDgIzFgX4EduAqkEPuphhOh9q'</span><span style="color: #007700;">,<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #dd0000;">'password'&nbsp;</span><span style="color: #007700;">=&gt;&nbsp;</span><span style="color: #dd0000;">'$2y$13$kkgpvJ8lnjKo8RuoR30ay.RjDf15bMcHIF7Vz1zz/6viYG5xJExU6'</span><span style="color: #007700;">,<br />&nbsp;&nbsp;&nbsp;&nbsp;],<br />];</span></code></pre>
<p>You may give an alias to a row so that later in your test, you may refer to the row via the alias. In the above example, the two rows are aliased as <code>user1</code> and <code>user2</code>, respectively.</p>
<p>Also, you do not need to specify the data for auto-incremental columns. Yii will automatically fill the actual values into the rows when the fixture is being loaded.</p>
<blockquote>
<p>Tip: You may customize the location of the data file by setting the <a href="http://www.yiiframework.com/doc-2.0/yii-test-activefixture.html#$dataFile-detail">yii\test\ActiveFixture::$dataFile</a> property. You may also override <a href="http://www.yiiframework.com/doc-2.0/yii-test-activefixture.html#getData%28%29-detail">yii\test\ActiveFixture::getData()</a> to provide the data.</p>
</blockquote>
<p>As we described earlier, a fixture may depend on other fixtures. For example, <code>UserProfileFixture</code> depends on <code>UserFixture</code> because the user profile table contains a foreign key pointing to the user table. The dependency is specified via the <a href="http://www.yiiframework.com/doc-2.0/yii-test-fixture.html#$depends-detail">yii\test\Fixture::$depends</a> property, like the following,</p>
<pre><code class="language-php"><span style="color: #007700;">namespace&nbsp;</span><span style="color: #0000bb;">app</span><span style="color: #007700;">\</span><span style="color: #0000bb;">tests</span><span style="color: #007700;">\</span><span style="color: #0000bb;">fixtures</span><span style="color: #007700;">;<br /><br />use&nbsp;</span><span style="color: #0000bb;">yii</span><span style="color: #007700;">\</span><span style="color: #0000bb;">test</span><span style="color: #007700;">\</span><span style="color: #0000bb;">ActiveFixture</span><span style="color: #007700;">;<br /><br />class&nbsp;</span><span style="color: #0000bb;">UserProfileFixture&nbsp;</span><span style="color: #007700;">extends&nbsp;</span><span style="color: #0000bb;">ActiveFixture<br /></span><span style="color: #007700;">{<br />&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;</span><span style="color: #0000bb;">$modelClass&nbsp;</span><span style="color: #007700;">=&nbsp;</span><span style="color: #dd0000;">'app\models\UserProfile'</span><span style="color: #007700;">;<br />&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;</span><span style="color: #0000bb;">$depends&nbsp;</span><span style="color: #007700;">=&nbsp;[</span><span style="color: #dd0000;">'app\tests\fixtures\UserFixture'</span><span style="color: #007700;">];<br />}</span></code></pre>
<p>In the above, we have shown how to define a fixture about a DB table. To define a fixture not related with DB (e.g. a fixture about certain files and directories), you may extend from the more general base class <a href="http://www.yiiframework.com/doc-2.0/yii-test-fixture.html">yii\test\Fixture</a> and override the <a href="http://www.yiiframework.com/doc-2.0/yii-test-fixture.html#load%28%29-detail">load()</a> and <a href="http://www.yiiframework.com/doc-2.0/yii-test-fixture.html#unload%28%29-detail">unload()</a> methods.</p>
<h2>Using Fixtures <a href="http://www.yiiframework.com/doc-2.0/guide-test-fixture.html#using-fixtures" name="using-fixtures">&para;</a></h2>
<p>If you are using <a href="http://codeception.com/">CodeCeption</a> to test your code, you should consider using the <code>yii2-codeception</code> extension which has the built-in support for loading and accessing fixtures. If you are using other testing frameworks, you may use <a href="http://www.yiiframework.com/doc-2.0/yii-test-fixturetrait.html">yii\test\FixtureTrait</a> in your test cases to achieve the same goal.</p>
<p>In the following we will describe how to write a <code>UserProfile</code> unit test class using <code>yii2-codeception</code>.</p>
<p>In your unit test class extending <a href="http://www.yiiframework.com/doc-2.0/yii-codeception-dbtestcase.html">yii\codeception\DbTestCase</a> or <a href="http://www.yiiframework.com/doc-2.0/yii-codeception-testcase.html">yii\codeception\TestCase</a>, declare which fixtures you want to use in the <a href="http://www.yiiframework.com/doc-2.0/yii-test-fixturetrait.html#fixtures%28%29-detail">fixtures()</a> method. For example,</p>
<pre><code class="language-php"><span style="color: #007700;">namespace&nbsp;</span><span style="color: #0000bb;">app</span><span style="color: #007700;">\</span><span style="color: #0000bb;">tests</span><span style="color: #007700;">\</span><span style="color: #0000bb;">unit</span><span style="color: #007700;">\</span><span style="color: #0000bb;">models</span><span style="color: #007700;">;<br /><br />use&nbsp;</span><span style="color: #0000bb;">yii</span><span style="color: #007700;">\</span><span style="color: #0000bb;">codeception</span><span style="color: #007700;">\</span><span style="color: #0000bb;">DbTestCase</span><span style="color: #007700;">;<br />use&nbsp;</span><span style="color: #0000bb;">app</span><span style="color: #007700;">\</span><span style="color: #0000bb;">tests</span><span style="color: #007700;">\</span><span style="color: #0000bb;">fixtures</span><span style="color: #007700;">\</span><span style="color: #0000bb;">UserProfileFixture</span><span style="color: #007700;">;<br /><br />class&nbsp;</span><span style="color: #0000bb;">UserProfileTest&nbsp;</span><span style="color: #007700;">extends&nbsp;</span><span style="color: #0000bb;">DbTestCase<br /></span><span style="color: #007700;">{<br />&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;function&nbsp;</span><span style="color: #0000bb;">fixtures</span><span style="color: #007700;">()<br />&nbsp;&nbsp;&nbsp;&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;[<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #dd0000;">'profiles'&nbsp;</span><span style="color: #007700;">=&gt;&nbsp;</span><span style="color: #0000bb;">UserProfileFixture</span><span style="color: #007700;">::</span><span style="color: #0000bb;">className</span><span style="color: #007700;">(),<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;];<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br /><br />&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #ff8000;">//&nbsp;...test&nbsp;methods...<br /></span><span style="color: #007700;">}</span></code></pre>
<p>The fixtures listed in the <code>fixtures()</code> method will be automatically loaded before running every test method in the test case and unloaded after finishing every test method. And as we described before, when a fixture is being loaded, all its dependent fixtures will be automatically loaded first. In the above example, because <code>UserProfileFixture</code> depends on <code>UserFixture</code>, when running any test method in the test class, two fixtures will be loaded sequentially: <code>UserFixture</code> and <code>UserProfileFixture</code>.</p>
<p>When specifying fixtures in <code>fixtures()</code>, you may use either a class name or a configuration array to refer to a fixture. The configuration array will let you customize the fixture properties when the fixture is loaded.</p>
<p>You may also assign an alias to a fixture. In the above example, the <code>UserProfileFixture</code> is aliased as <code>profiles</code>. In the test methods, you may then access a fixture object using its alias. For example, <code>$this-&gt;profiles</code> will return the <code>UserProfileFixture</code> object.</p>
<p>Because <code>UserProfileFixture</code> extends from <code>ActiveFixture</code>, you may further use the following syntax to access the data provided by the fixture:</p>
<pre><code class="language-php"><span style="color: #ff8000;">//&nbsp;returns&nbsp;the&nbsp;data&nbsp;row&nbsp;aliased&nbsp;as&nbsp;'user1'<br /></span><span style="color: #0000bb;">$row&nbsp;</span><span style="color: #007700;">=&nbsp;</span><span style="color: #0000bb;">$this</span><span style="color: #007700;">-&gt;</span><span style="color: #0000bb;">profiles</span><span style="color: #007700;">[</span><span style="color: #dd0000;">'user1'</span><span style="color: #007700;">];<br /></span><span style="color: #ff8000;">//&nbsp;returns&nbsp;the&nbsp;UserProfile&nbsp;model&nbsp;corresponding&nbsp;to&nbsp;the&nbsp;data&nbsp;row&nbsp;aliased&nbsp;as&nbsp;'user1'<br /></span><span style="color: #0000bb;">$profile&nbsp;</span><span style="color: #007700;">=&nbsp;</span><span style="color: #0000bb;">$this</span><span style="color: #007700;">-&gt;</span><span style="color: #0000bb;">profiles</span><span style="color: #007700;">(</span><span style="color: #dd0000;">'user1'</span><span style="color: #007700;">);<br /></span><span style="color: #ff8000;">//&nbsp;traverse&nbsp;every&nbsp;data&nbsp;row&nbsp;in&nbsp;the&nbsp;fixture<br /></span><span style="color: #007700;">foreach&nbsp;(</span><span style="color: #0000bb;">$this</span><span style="color: #007700;">-&gt;</span><span style="color: #0000bb;">profiles&nbsp;</span><span style="color: #007700;">as&nbsp;</span><span style="color: #0000bb;">$row</span><span style="color: #007700;">)&nbsp;...</span></code></pre>
<blockquote>
<p>Info: <code>$this-&gt;profiles</code> is still of <code>UserProfileFixture</code> type. The above access features are implemented through PHP magic methods.</p>
</blockquote>
<h2>Defining and Using Global Fixtures <a href="http://www.yiiframework.com/doc-2.0/guide-test-fixture.html#defining-and-using-global-fixtures" name="defining-and-using-global-fixtures">&para;</a></h2>
<p>The fixtures described above are mainly used by individual test cases. In most cases, you also need some global fixtures that are applied to ALL or many test cases. An example is <a href="http://www.yiiframework.com/doc-2.0/yii-test-initdbfixture.html">yii\test\InitDbFixture</a> which does two things:</p>
<ul>
<li>Perform some common initialization tasks by executing a script located at <code>@app/tests/fixtures/initdb.php</code>;</li>
<li>Disable the database integrity check before loading other DB fixtures, and re-enable it after other DB fixtures are unloaded.</li>
</ul>
<p>Using global fixtures is similar to using non-global ones. The only difference is that you declare these fixtures in <a href="http://www.yiiframework.com/doc-2.0/yii-test-fixturetrait.html#globalFixtures%28%29-detail">yii\codeception\TestCase::globalFixtures()</a> instead of <code>fixtures()</code>. When a test case loads fixtures, it will first load global fixtures and then non-global ones.</p>
<p>By default, <a href="http://www.yiiframework.com/doc-2.0/yii-codeception-dbtestcase.html">yii\codeception\DbTestCase</a> already declares <code>InitDbFixture</code> in its <code>globalFixtures()</code> method. This means you only need to work with <code>@app/tests/fixtures/initdb.php</code> if you want to do some initialization work before each test. You may otherwise simply focus on developing each individual test case and the corresponding fixtures.</p>
<h2>Organizing Fixture Classes and Data Files <a href="http://www.yiiframework.com/doc-2.0/guide-test-fixture.html#organizing-fixture-classes-and-data-files" name="organizing-fixture-classes-and-data-files">&para;</a></h2>
<p>By default, fixture classes look for the corresponding data files under the <code>data</code> folder which is a sub-folder of the folder containing the fixture class files. You can follow this convention when working with simple projects. For big projects, chances are that you often need to switch different data files for the same fixture class for different tests. We thus recommend that you organize the data files in a hierarchical way that is similar to your class namespaces. For example,</p>
<pre><code># under folder tests\unit\fixtures

data\
    components\
        fixture_data_file1.php
        fixture_data_file2.php
        ...
        fixture_data_fileN.php
    models\
        fixture_data_file1.php
        fixture_data_file2.php
        ...
        fixture_data_fileN.php
# and so on
</code></pre>
<p>In this way you will avoid collision of fixture data files between tests and use them as you need.</p>
<blockquote>
<p>Note: In the example above fixture files are named only for example purpose. In real life you should name them according to which fixture class your fixture classes are extending from. For example, if you are extending from <a href="http://www.yiiframework.com/doc-2.0/yii-test-activefixture.html">yii\test\ActiveFixture</a> for DB fixtures, you should use DB table names as the fixture data file names; If you are extending for <a href="http://www.yiiframework.com/doc-2.0/yii-mongodb-activefixture.html">yii\mongodb\ActiveFixture</a> for MongoDB fixtures, you should use collection names as the file names.</p>
</blockquote>
<p>The similar hierarchy can be used to organize fixture class files. Instead of using <code>data</code> as the root directory, you may want to use <code>fixtures</code> as the root directory to avoid conflict with the data files.</p>
<h2>Summary <a href="http://www.yiiframework.com/doc-2.0/guide-test-fixture.html#summary" name="summary">&para;</a></h2>
<p>In the above, we have described how to define and use fixtures. Below we summarize the typical workflow of running unit tests related with DB:</p>
<ol>
<li>Use <code>yii migrate</code> tool to upgrade your test database to the latest version;</li>
<li>Run a test case:
<ul>
<li>Load fixtures: clean up the relevant DB tables and populate them with fixture data;</li>
<li>Perform the actual test;</li>
<li>Unload fixtures.</li>
</ul>
</li>
<li>Repeat Step 2 until all tests finish.</li>
</ol>
</div>