<h1 style="box-sizing: border-box; margin: 20px 0px 10px; font-size: 36px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.1; color: #333333; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;">Jquery UI Widgets</h1>
<blockquote style="box-sizing: border-box; padding: 10px 20px; margin: 0px 0px 20px; font-size: 14px; border-left-width: 5px; border-left-style: solid; border-left-color: #eeeeee; color: #333333; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;">
<p style="box-sizing: border-box; margin: 0px;">Note: This section is under development.</p>
</blockquote>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #333333; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;">Out of the box, Yii includes support for the<span class="Apple-converted-space">&nbsp;</span><a style="box-sizing: border-box; color: #428bca; text-decoration: none; background: transparent;" href="http://api.jqueryui.com/">jQuery UI</a><span class="Apple-converted-space">&nbsp;</span>library. jQuery UI is a curated set of user interface interactions, effects, widgets, and themes built on top of the jQuery JavaScript Library.</p>
<h2 style="box-sizing: border-box; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.1; color: #333333; margin-top: 20px; margin-bottom: 10px; font-size: 30px; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;">Yii widgets</h2>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #333333; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;">Most complex jQuery UI components are wrapped into Yii widgets to allow more robust syntax and integrate with framework features. All widgets belong to<span class="Apple-converted-space">&nbsp;</span><code style="box-sizing: border-box; font-family: Menlo, Monaco, Consolas, 'Courier New', monospace; font-size: 13px; padding: 2px 4px; color: #c7254e; border-top-left-radius: 4px; border-top-right-radius: 4px; border-bottom-right-radius: 4px; border-bottom-left-radius: 4px; background-color: #f9f2f4;">\yii\jui</code><span class="Apple-converted-space">&nbsp;</span>namespace:</p>
<ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 10px; color: #333333; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;">
<li style="box-sizing: border-box;"><a style="box-sizing: border-box; color: #428bca; text-decoration: none; background: transparent;" href="http://www.yiiframework.com/doc-2.0/yii-jui-accordion.html">Accordion</a></li>
<li style="box-sizing: border-box;"><a style="box-sizing: border-box; color: #428bca; text-decoration: none; background: transparent;" href="http://www.yiiframework.com/doc-2.0/yii-jui-autocomplete.html">AutoComplete</a></li>
<li style="box-sizing: border-box;"><a style="box-sizing: border-box; color: #428bca; text-decoration: none; background: transparent;" href="http://www.yiiframework.com/doc-2.0/yii-jui-datepicker.html">DatePicker</a></li>
<li style="box-sizing: border-box;"><a style="box-sizing: border-box; color: #428bca; text-decoration: none; background: transparent;" href="http://www.yiiframework.com/doc-2.0/yii-jui-dialog.html">Dialog</a></li>
<li style="box-sizing: border-box;"><a style="box-sizing: border-box; color: #428bca; text-decoration: none; background: transparent;" href="http://www.yiiframework.com/doc-2.0/yii-jui-draggable.html">Draggable</a></li>
<li style="box-sizing: border-box;"><a style="box-sizing: border-box; color: #428bca; text-decoration: none; background: transparent;" href="http://www.yiiframework.com/doc-2.0/yii-jui-droppable.html">Droppable</a></li>
<li style="box-sizing: border-box;"><a style="box-sizing: border-box; color: #428bca; text-decoration: none; background: transparent;" href="http://www.yiiframework.com/doc-2.0/yii-jui-menu.html">Menu</a></li>
<li style="box-sizing: border-box;"><a style="box-sizing: border-box; color: #428bca; text-decoration: none; background: transparent;" href="http://www.yiiframework.com/doc-2.0/yii-jui-progressbar.html">ProgressBar</a></li>
<li style="box-sizing: border-box;"><a style="box-sizing: border-box; color: #428bca; text-decoration: none; background: transparent;" href="http://www.yiiframework.com/doc-2.0/yii-jui-resizable.html">Resizable</a></li>
<li style="box-sizing: border-box;"><a style="box-sizing: border-box; color: #428bca; text-decoration: none; background: transparent;" href="http://www.yiiframework.com/doc-2.0/yii-jui-selectable.html">Selectable</a></li>
<li style="box-sizing: border-box;"><a style="box-sizing: border-box; color: #428bca; text-decoration: none; background: transparent;" href="http://www.yiiframework.com/doc-2.0/yii-jui-slider.html">Slider</a></li>
<li style="box-sizing: border-box;"><a style="box-sizing: border-box; color: #428bca; text-decoration: none; background: transparent;" href="http://www.yiiframework.com/doc-2.0/yii-jui-sliderinput.html">SliderInput</a></li>
<li style="box-sizing: border-box;"><a style="box-sizing: border-box; color: #428bca; text-decoration: none; background: transparent;" href="http://www.yiiframework.com/doc-2.0/yii-jui-sortable.html">Sortable</a></li>
<li style="box-sizing: border-box;"><a style="box-sizing: border-box; color: #428bca; text-decoration: none; background: transparent;" href="http://www.yiiframework.com/doc-2.0/yii-jui-spinner.html">Spinner</a></li>
<li style="box-sizing: border-box;"><a style="box-sizing: border-box; color: #428bca; text-decoration: none; background: transparent;" href="http://www.yiiframework.com/doc-2.0/yii-jui-tabs.html">Tabs</a></li>
</ul>